# Imagem base - Nginx Alpine 
FROM nginx:alpine 

# Copia os arquivos do website para o diretorio do Nginx
COPY website/ /usr/share/nginx/html/

# Expõe a porta 80 (documentação - não abre a porta realmente)
EXPOSE 80

# Comando padrão quando o container iniciar
CMD ["nginx", "-g", "daemon off;"]